site_name: szurubooru_client

theme:
  name: "material"

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          allow_inspection: true
          load_external_modules: true
